"""
Django settings for cms_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# SECURITY FIX
# Fix ID: F1 – Secure secret management using environment variables
# Weakness ID: W1
# STRIDE: Information Disclosure
# OWASP Top 10: A02 Cryptographic Failures
# CWE: CWE-798 Use of Hard-coded Credentials
# CIA: Confidentiality
# ASVS: V13 – Secret Management
# D3FEND: D3-SM Secure Storage
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY FIX
# Fix ID: F2 – Secure deployment configuration
# Weakness ID: W2
# STRIDE: Information Disclosure
# OWASP Top 10: A05 Security Misconfiguration
# CWE: CWE-489 Active Debug Code, CWE-16 Configuration
# CIA: Confidentiality
# ASVS: V14 – Configuration
# D3FEND: D3-CFG Configuration Hardening
DEBUG = False


# SECURITY FIX
# Fix ID: F2 – Restrict allowed hosts
# Weakness ID: W2
# STRIDE: Information Disclosure
# OWASP Top 10: A05 Security Misconfiguration
# CWE: CWE-16 Configuration
# CIA: Confidentiality
# ASVS: V14 – Configuration
# D3FEND: D3-CFG Configuration Hardening
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "complaints",
    "axes",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]


ROOT_URLCONF = "cms_project.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.dashboard_link",
            ],
        },
    },
]


WSGI_APPLICATION = "cms_project.wsgi.application"


# SECURITY FIX
# Fix ID: F1 – Secure database credentials using environment variables
# Weakness ID: W1
# STRIDE: Information Disclosure
# OWASP Top 10: A02 Cryptographic Failures
# CWE: CWE-798 Use of Hard-coded Credentials
# CIA: Confidentiality
# ASVS: V13 – Secret Management
# D3FEND: D3-SM Secure Storage
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "post_login_redirect"
LOGOUT_REDIRECT_URL = "login"

# SECURITY FIX
# Fix ID: F4 – Brute-force protection and rate limiting on login
# Weakness ID: W4
# STRIDE: Spoofing / Denial of Service
# OWASP Top 10: A07 Identification and Authentication Failures
# CWE: CWE-307 Improper Restriction of Excessive Authentication Attempts
# CIA: Confidentiality / Availability
# ASVS: V6 – Authentication Security
# D3FEND: D3-ANET Account Locking / Network Traffic Filtering
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS = True


# SECURITY FIX
# Fix ID: F5 – Enforce HTTPS and secure session cookies
# Weakness ID: W5
# STRIDE: Information Disclosure
# OWASP Top 10: A02 Cryptographic Failures
# CWE: CWE-319 Cleartext Transmission of Sensitive Information
# CIA: Confidentiality
# ASVS: V9 – Communications Security
# D3FEND: D3-MENCR Encryption

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True