# Generated by Django 5.2.8 on 2025-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='UNASSIGNED', max_length=10),
        ),
    ]
